---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fredo.
--- DateTime: 9/28/23 1:10 AM
---

local n = 5000000
local prime = {}
local primes = {}

for i = 2, n do prime[i] = true end

for i = 2, n do
    if prime[i] then
        primes[#primes+1] = i
        for j = i*2, n, i do prime[j] = false end
    end
end