---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fredo.
--- DateTime: 9/28/23 1:10 AM
---

local n = 5000000
local composite = {}
local primes = {}

for i = 2, n do
    if not composite[i] then
        primes[#primes+1] = i
        for j = i*2, n, i do composite[j] = true end
    end
end